---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  ansible.builtin.apt:
    name:
      - curl
      - git
      - rsync
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - python3-pip
    state: present

- name: Create app directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ app_dir }}"
    - "{{ data_dir }}"
    - "{{ data_dir }}/wordpress"
    - "{{ data_dir }}/mariadb"
